version: "3.7"

services:
  project_db:
    image: postgres:13
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stock_db
    ports:
      - "5432:5432"

volumes:
  postgres-data: