# Generated by Django 4.2.1 on 2023-06-06 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0002_animal_type_alter_animal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('market', models.CharField(blank=True, choices=[('KOSPI', 'KOSPI 종합'), ('KOSDAQ', 'KOSDAQ 종합')], max_length=10, null=True)),
                ('recommended_date', models.DateField(blank=True, null=True)),
                ('recommended_price', models.IntegerField(blank=True, null=True)),
                ('prev_close', models.IntegerField(blank=True, null=True)),
                ('dividend_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_api.stockcompany')),
            ],
        ),
    ]
