# Generated by Django 4.2.1 on 2023-06-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0003_stockcompany_recommendedstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedstock',
            name='dividend_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
