# Generated by Django 4.2.1 on 2023-06-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0004_alter_recommendedstock_dividend_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_sent_topic', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
