# Generated by Django 4.2.1 on 2023-06-09 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0005_stockreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='stockreport',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockreport',
            name='pdf_sent_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockreport',
            name='pdf_summerize',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockreport',
            name='pdf_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockreport',
            name='report_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockreport',
            name='stock_broker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockreport',
            name='target_opinion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockreport',
            name='target_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockreport',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockreport',
            name='wdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockreport',
            name='pdf_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_api.pdfname'),
        ),
    ]
