# Generated by Django 4.2.1 on 2023-06-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0006_pdfname_stockreport_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreport',
            name='pdf_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='PdfName',
        ),
    ]
